version: '3'
services:
  jira:
    container_name: jira
    image: atlassian/jira-software:latest
    environment:
      - ATL_PROXY_NAME=${JIRA_PROXY_NAME}
      - ATL_PROXY_PORT=80
      - ATL_TOMCAT_SCHEME=http
    links:
      - jiradb
    volumes:
      - /app/atlassian/application-data/jira:/var/atlassian/application-data/jira
      - /app/atlassian/docker/certs/cacerts:/opt/java/openjdk/jre/lib/security/cacerts
    depends_on:
      - jiradb

  confluence:
    container_name: confluence
    image: atlassian/confluence-server:latest
    environment:
      - ATL_PROXY_NAME=${CONFLUENCE_PROXY_NAME}
      - ATL_PROXY_PORT=80
      - ATL_TOMCAT_SCHEME=http
    links:
      - confluencedb
    volumes:
      - /app/atlassian/application-data/confluence:/var/atlassian/application-data/confluence
      - /app/atlassian/docker/certs/cacerts:/opt/java/openjdk/jre/lib/security/cacerts
    depends_on:
      - confluencedb

  bitbucket:
    container_name: bitbucket
    image: atlassian/bitbucket-server:latest
    environment:
      - SERVER_PROXY_NAME=${BITBUCKET_PROXY_NAME}
      - SERVER_PROXY_PORT=80
      - SERVER_SCHEME=http
    links:
      - bitbucketdb
    volumes:
      - /app/atlassian/application-data/bitbucket:/var/atlassian/application-data/bitbucket
      - /app/atlassian/docker/certs/cacerts:/opt/java/openjdk/jre/lib/security/cacerts
    depends_on:
      - bitbucketdb

  jiradb:
    image: postgres:9.4
    restart: always
    volumes:
      - /app/lib/postgresql/jira:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=${JIRA_DB_NAME}
      - POSTGRES_USER=${JIRA_DB_USER}
      - POSTGRES_PASSWORD=${JIRA_DB_PASSWORD}
    stop_grace_period: ${STOP_GRACE_PERIOD}

  confluencedb:
    image: postgres:9.4
    restart: always
    volumes:
      - /app/lib/postgresql/confluence:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=${CONFLUENCE_DB_NAME}
      - POSTGRES_USER=${CONFLUENCE_DB_USER}
      - POSTGRES_PASSWORD=${CONFLUENCE_DB_PASSWORD}
    stop_grace_period: ${STOP_GRACE_PERIOD}

  bitbucketdb:
    image: postgres:9.4
    restart: always
    volumes:
      - /app/lib/postgresql/bitbucket:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=${BITBUCKET_DB_NAME}
      - POSTGRES_USER=${BITBUCKET_DB_USER}
      - POSTGRES_PASSWORD=${BITBUCKET_DB_PASSWORD}
    stop_grace_period: ${STOP_GRACE_PERIOD}

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - jira
      - confluence
      - bitbucket
    ports:
      - "80:80"
    networks:
      default:
        aliases:
          - ${JIRA_PROXY_NAME}
          - ${CONFLUENCE_PROXY_NAME}
          - ${BITBUCKET_PROXY_NAME}
    stop_grace_period: ${STOP_GRACE_PERIOD}
